Repository peaqnetwork/substrate-faucet, pull requests merged in 2023-02, with the labels that each got.

#2 Add multiple faucets/library upgrade/Refine code
  README.md
  app/faucet.py
  requirements.txt
Labels: size/L

#3 add: configmap for multinode
  charts/substrate-faucet/templates/deployment.yaml
  charts/substrate-faucet/values.yaml
Labels: size/S

#4 Fix errors
  app/faucet.py
Labels: size/XS, lgtm
